version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"  
    networks:
      - app-network

  backend:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"  
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
