services:
  frontend:
    build:
      context: ./client
    ports:
      - "8080:80"  
    networks:
      - app-network

  backend:
    build:
      context: ./service
    ports:
      - "9090:9090"  
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
